apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudio-backend
  namespace: cloudio
  labels:
    app: cloudio-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudio-backend
  template:
    metadata:
      labels:
        app: cloudio-backend
    spec:
      containers:
      - name: backend
        image: omerhaim/cloudio-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cloudio-backend
  namespace: cloudio
  labels:
    app: cloudio-backend
spec:
  type: NodePort
  selector:
    app: cloudio-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30081
